//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDDProject.MVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Antlia_DBEntities : DbContext
    {
        public Antlia_DBEntities()
            : base("name=Antlia_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MOVIMENTO_MANUAL> MOVIMENTO_MANUAL { get; set; }
        public virtual DbSet<Produto> Produtoes { get; set; }
        public virtual DbSet<PRODUTO_COSIF> PRODUTO_COSIF { get; set; }
    
        public virtual int prInserirMovimentosManuais(string cOD_PRODUTO, string cOD_COSIF, Nullable<int> dAT_ANO, Nullable<int> dAT_MES, Nullable<int> nUM_LANCAMENTO, Nullable<double> vAL_VALOR, string dES_DESCRICAO, Nullable<System.DateTime> dAT_MOVIMENTO, string cOD_USUARIO)
        {
            var cOD_PRODUTOParameter = cOD_PRODUTO != null ?
                new ObjectParameter("COD_PRODUTO", cOD_PRODUTO) :
                new ObjectParameter("COD_PRODUTO", typeof(string));
    
            var cOD_COSIFParameter = cOD_COSIF != null ?
                new ObjectParameter("COD_COSIF", cOD_COSIF) :
                new ObjectParameter("COD_COSIF", typeof(string));
    
            var dAT_ANOParameter = dAT_ANO.HasValue ?
                new ObjectParameter("DAT_ANO", dAT_ANO) :
                new ObjectParameter("DAT_ANO", typeof(int));
    
            var dAT_MESParameter = dAT_MES.HasValue ?
                new ObjectParameter("DAT_MES", dAT_MES) :
                new ObjectParameter("DAT_MES", typeof(int));
    
            var nUM_LANCAMENTOParameter = nUM_LANCAMENTO.HasValue ?
                new ObjectParameter("NUM_LANCAMENTO", nUM_LANCAMENTO) :
                new ObjectParameter("NUM_LANCAMENTO", typeof(int));
    
            var vAL_VALORParameter = vAL_VALOR.HasValue ?
                new ObjectParameter("VAL_VALOR", vAL_VALOR) :
                new ObjectParameter("VAL_VALOR", typeof(double));
    
            var dES_DESCRICAOParameter = dES_DESCRICAO != null ?
                new ObjectParameter("DES_DESCRICAO", dES_DESCRICAO) :
                new ObjectParameter("DES_DESCRICAO", typeof(string));
    
            var dAT_MOVIMENTOParameter = dAT_MOVIMENTO.HasValue ?
                new ObjectParameter("DAT_MOVIMENTO", dAT_MOVIMENTO) :
                new ObjectParameter("DAT_MOVIMENTO", typeof(System.DateTime));
    
            var cOD_USUARIOParameter = cOD_USUARIO != null ?
                new ObjectParameter("COD_USUARIO", cOD_USUARIO) :
                new ObjectParameter("COD_USUARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prInserirMovimentosManuais", cOD_PRODUTOParameter, cOD_COSIFParameter, dAT_ANOParameter, dAT_MESParameter, nUM_LANCAMENTOParameter, vAL_VALORParameter, dES_DESCRICAOParameter, dAT_MOVIMENTOParameter, cOD_USUARIOParameter);
        }
    
        public virtual int prInserirProdutos(string cOD_PRODUTO, string dES_PRODUTO, string sTA_STATUS)
        {
            var cOD_PRODUTOParameter = cOD_PRODUTO != null ?
                new ObjectParameter("COD_PRODUTO", cOD_PRODUTO) :
                new ObjectParameter("COD_PRODUTO", typeof(string));
    
            var dES_PRODUTOParameter = dES_PRODUTO != null ?
                new ObjectParameter("DES_PRODUTO", dES_PRODUTO) :
                new ObjectParameter("DES_PRODUTO", typeof(string));
    
            var sTA_STATUSParameter = sTA_STATUS != null ?
                new ObjectParameter("STA_STATUS", sTA_STATUS) :
                new ObjectParameter("STA_STATUS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prInserirProdutos", cOD_PRODUTOParameter, dES_PRODUTOParameter, sTA_STATUSParameter);
        }
    
        public virtual ObjectResult<prSelecionaMOVIMENTO_MANUAL_Result> prSelecionaMOVIMENTO_MANUAL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prSelecionaMOVIMENTO_MANUAL_Result>("prSelecionaMOVIMENTO_MANUAL");
        }
    
        public virtual ObjectResult<prSelecionaProducoCosif_Result> prSelecionaProducoCosif()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prSelecionaProducoCosif_Result>("prSelecionaProducoCosif");
        }
    
        public virtual ObjectResult<SelecionaProduto_Result> SelecionaProduto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelecionaProduto_Result>("SelecionaProduto");
        }
    }
}
