//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDDProject.MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMENTO_MANUAL
    {
        public string COD_PRODUTO { get; set; }
        public string COD_COSIF { get; set; }
        public int DAT_ANO { get; set; }
        public int DAT_MES { get; set; }
        public int NUM_LANCAMENTO { get; set; }
        public double VAL_VALOR { get; set; }
        public string DES_DESCRICAO { get; set; }
        public System.DateTime DAT_MOVIMENTO { get; set; }
        public string COD_USUARIO { get; set; }
    
        public virtual PRODUTO_COSIF PRODUTO_COSIF { get; set; }
    }
}
